try:
    5/0
except Exception as err:
    print(f"We caught this: {err}")

