try:
    prynt("3")
except Exception as err:
    print(f"We caught this: {err}")

