try:
    int("a")
except Exception as err:
    print(f"We caught this: {err}")

